# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_geophysics_ui.ui'
#
# Created: Fri Dec 23 15:50:31 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogGeo(object):
    def setupUi(self, DialogGeo):
        DialogGeo.setObjectName(_fromUtf8("DialogGeo"))
        DialogGeo.resize(676, 695)
        DialogGeo.setMinimumSize(QtCore.QSize(540, 682))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        DialogGeo.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconPAI.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogGeo.setWindowIcon(icon)
        DialogGeo.setAutoFillBackground(False)
        self.gridLayout_24 = QtGui.QGridLayout(DialogGeo)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.label_49 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_24.addWidget(self.label_49, 4, 0, 1, 3)
        self.label_30 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_24.addWidget(self.label_30, 4, 10, 1, 1)
        self.gridLayout_27 = QtGui.QGridLayout()
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.lineEdit_settore = QtGui.QLineEdit(DialogGeo)
        self.lineEdit_settore.setEnabled(True)
        self.lineEdit_settore.setMinimumSize(QtCore.QSize(60, 21))
        self.lineEdit_settore.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_settore.setFont(font)
        self.lineEdit_settore.setText(_fromUtf8(""))
        self.lineEdit_settore.setObjectName(_fromUtf8("lineEdit_settore"))
        self.gridLayout_27.addWidget(self.lineEdit_settore, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_27.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_27, 6, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_rec_tot = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.label_27 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_34 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_43 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogGeo)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.label_42 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 2, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_sort = QtGui.QPushButton(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon1)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon2)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon3)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon4)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon5)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(DialogGeo)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon6)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_first_rec = QtGui.QPushButton(DialogGeo)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon7)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 2, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogGeo)
        self.pushButton_delete.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon8)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout.addWidget(self.pushButton_delete, 1, 2, 1, 1)
        self.pushButton_next_rec = QtGui.QPushButton(DialogGeo)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon9)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon10)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogGeo)
        self.pushButton_prev_rec.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon11)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_2, 0, 0, 1, 17)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_5 = QtGui.QLabel(DialogGeo)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_metodo = QtGui.QComboBox(DialogGeo)
        self.comboBox_metodo.setObjectName(_fromUtf8("comboBox_metodo"))
        self.comboBox_metodo.addItem(_fromUtf8(""))
        self.comboBox_metodo.addItem(_fromUtf8(""))
        self.comboBox_metodo.addItem(_fromUtf8(""))
        self.comboBox_metodo.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_metodo, 0, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_6, 3, 12, 1, 1)
        self.gridLayout_29 = QtGui.QGridLayout()
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.lineEdit_griglia = QtGui.QLineEdit(DialogGeo)
        self.lineEdit_griglia.setEnabled(True)
        self.lineEdit_griglia.setMinimumSize(QtCore.QSize(61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_griglia.setFont(font)
        self.lineEdit_griglia.setText(_fromUtf8(""))
        self.lineEdit_griglia.setObjectName(_fromUtf8("lineEdit_griglia"))
        self.gridLayout_29.addWidget(self.lineEdit_griglia, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_29.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_29, 6, 2, 1, 1)
        self.gridLayout_26 = QtGui.QGridLayout()
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.label_61 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_26.addWidget(self.label_61, 1, 0, 1, 1)
        self.lineEdit_anno = QtGui.QLineEdit(DialogGeo)
        self.lineEdit_anno.setEnabled(True)
        self.lineEdit_anno.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_anno.setAutoFillBackground(True)
        self.lineEdit_anno.setText(_fromUtf8(""))
        self.lineEdit_anno.setObjectName(_fromUtf8("lineEdit_anno"))
        self.gridLayout_26.addWidget(self.lineEdit_anno, 0, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_26, 3, 13, 1, 1)
        self.label_50 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_24.addWidget(self.label_50, 2, 0, 1, 2)
        self.label_47 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_24.addWidget(self.label_47, 4, 12, 1, 1)
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.lineEdit_progetto = QtGui.QLineEdit(DialogGeo)
        self.lineEdit_progetto.setText(_fromUtf8(""))
        self.lineEdit_progetto.setObjectName(_fromUtf8("lineEdit_progetto"))
        self.gridLayout_25.addWidget(self.lineEdit_progetto, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_25.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 3, 10, 1, 1)
        self.line_8 = QtGui.QFrame(DialogGeo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_24.addWidget(self.line_8, 1, 0, 1, 17)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lineEdit_quota_2 = QtGui.QLineEdit(DialogGeo)
        self.lineEdit_quota_2.setObjectName(_fromUtf8("lineEdit_quota_2"))
        self.gridLayout_9.addWidget(self.lineEdit_quota_2, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_9.addWidget(self.label_15, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_9, 6, 12, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lineEdit_pdc = QtGui.QLineEdit(DialogGeo)
        self.lineEdit_pdc.setMinimumSize(QtCore.QSize(4, 3))
        self.lineEdit_pdc.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_pdc.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_pdc.setObjectName(_fromUtf8("lineEdit_pdc"))
        self.gridLayout_7.addWidget(self.lineEdit_pdc, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_7, 6, 10, 1, 1)
        self.gridLayout_28 = QtGui.QGridLayout()
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.label_2 = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_28.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_area = QtGui.QComboBox(DialogGeo)
        self.comboBox_area.setEnabled(True)
        self.comboBox_area.setMaximumSize(QtCore.QSize(64, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_area.setFont(font)
        self.comboBox_area.setEditable(True)
        self.comboBox_area.setObjectName(_fromUtf8("comboBox_area"))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.setItemText(0, _fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.comboBox_area.addItem(_fromUtf8(""))
        self.gridLayout_28.addWidget(self.comboBox_area, 0, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_28, 6, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(9, 9, 95, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.textEdit_descrizione = QtGui.QTextEdit(self.tab)
        self.textEdit_descrizione.setGeometry(QtCore.QRect(9, 31, 634, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione.setFont(font)
        self.textEdit_descrizione.setObjectName(_fromUtf8("textEdit_descrizione"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(9, 137, 69, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_interpretazione = QtGui.QTextEdit(self.tab)
        self.textEdit_interpretazione.setGeometry(QtCore.QRect(9, 159, 634, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione.setFont(font)
        self.textEdit_interpretazione.setObjectName(_fromUtf8("textEdit_interpretazione"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(9, 266, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 290, 631, 71))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lineEdit_data_schedatura = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_data_schedatura.setText(_fromUtf8(""))
        self.lineEdit_data_schedatura.setObjectName(_fromUtf8("lineEdit_data_schedatura"))
        self.gridLayout_12.addWidget(self.lineEdit_data_schedatura, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem1, 2, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_35 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_11.addWidget(self.label_35, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(248, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 1, 1, 1, 1)
        self.comboBox_schedatore = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_schedatore.setEditable(True)
        self.comboBox_schedatore.setObjectName(_fromUtf8("comboBox_schedatore"))
        self.gridLayout_11.addWidget(self.comboBox_schedatore, 0, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setEnabled(True)
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 30, 174, 80))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.gridLayout_30 = QtGui.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_30.setMargin(0)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.label_59 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_30.addWidget(self.label_59, 4, 0, 1, 1)
        self.label_60 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_30.addWidget(self.label_60, 2, 0, 1, 1)
        self.label_58 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_30.addWidget(self.label_58, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_30.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_30.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_30.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.label_65 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_30.addWidget(self.label_65, 0, 2, 1, 1)
        self.label_66 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_30.addWidget(self.label_66, 2, 2, 1, 1)
        self.label_67 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_30.addWidget(self.label_67, 4, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.tab_6)
        self.label_57.setGeometry(QtCore.QRect(9, 69, 291, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_6)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 100, 311, 162))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.formLayout_3 = QtGui.QFormLayout(self.horizontalLayoutWidget)
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setHorizontalSpacing(1)
        self.formLayout_3.setVerticalSpacing(5)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_51 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_51.setMaximumSize(QtCore.QSize(72, 150))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_51)
        self.lineEdit_range = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_range.sizePolicy().hasHeightForWidth())
        self.lineEdit_range.setSizePolicy(sizePolicy)
        self.lineEdit_range.setObjectName(_fromUtf8("lineEdit_range"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_range)
        self.lineEdit_max_prof = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_max_prof.sizePolicy().hasHeightForWidth())
        self.lineEdit_max_prof.setSizePolicy(sizePolicy)
        self.lineEdit_max_prof.setObjectName(_fromUtf8("lineEdit_max_prof"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_max_prof)
        self.label_54 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_54)
        self.label_53 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_53)
        self.label_52 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_52.setMaximumSize(QtCore.QSize(110, 16))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_52)
        self.lineEdit_risoluzione = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_risoluzione.sizePolicy().hasHeightForWidth())
        self.lineEdit_risoluzione.setSizePolicy(sizePolicy)
        self.lineEdit_risoluzione.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_risoluzione.setObjectName(_fromUtf8("lineEdit_risoluzione"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_risoluzione)
        self.lineEdit_5 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_55 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_55)
        self.lineEdit_ = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_.sizePolicy().hasHeightForWidth())
        self.lineEdit_.setSizePolicy(sizePolicy)
        self.lineEdit_.setObjectName(_fromUtf8("lineEdit_"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_)
        self.label_56 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_56)
        self.comboBox_frequenza = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_frequenza.setEnabled(True)
        self.comboBox_frequenza.setObjectName(_fromUtf8("comboBox_frequenza"))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.comboBox_frequenza.setItemText(0, _fromUtf8(""))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.comboBox_frequenza.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_frequenza)
        self.label_62 = QtGui.QLabel(self.tab_6)
        self.label_62.setGeometry(QtCore.QRect(340, 10, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_6)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 115, 46))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.gridLayout_22 = QtGui.QGridLayout(self.verticalLayoutWidget_2)
        self.gridLayout_22.setMargin(0)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_63 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_22.addWidget(self.label_63, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_22.addWidget(self.comboBox, 1, 0, 1, 1)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab_6)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(140, 10, 181, 46))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.gridLayout_23 = QtGui.QGridLayout(self.verticalLayoutWidget_3)
        self.gridLayout_23.setMargin(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.label_64 = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_23.addWidget(self.label_64, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_23.addWidget(self.comboBox_2, 1, 0, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.tab_6)
        self.dateEdit.setGeometry(QtCore.QRect(530, 30, 110, 22))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.label_68 = QtGui.QLabel(self.tab_6)
        self.label_68.setGeometry(QtCore.QRect(530, 10, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_69 = QtGui.QLabel(self.tab_6)
        self.label_69.setGeometry(QtCore.QRect(350, 130, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pushButton_draw_doc = QtGui.QPushButton(self.tab_5)
        self.pushButton_draw_doc.setGeometry(QtCore.QRect(456, 10, 196, 27))
        self.pushButton_draw_doc.setObjectName(_fromUtf8("pushButton_draw_doc"))
        self.pushButton = QtGui.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(345, 10, 105, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tableWidget_documentazione = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_documentazione.setGeometry(QtCore.QRect(0, 40, 661, 284))
        self.tableWidget_documentazione.setMinimumSize(QtCore.QSize(0, 284))
        self.tableWidget_documentazione.setMaximumSize(QtCore.QSize(16777215, 284))
        font = QtGui.QFont()
        font.setKerning(True)
        self.tableWidget_documentazione.setFont(font)
        self.tableWidget_documentazione.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_documentazione.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget_documentazione.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_documentazione.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_documentazione.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_documentazione.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_documentazione.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_documentazione.setRowCount(1)
        self.tableWidget_documentazione.setColumnCount(2)
        self.tableWidget_documentazione.setObjectName(_fromUtf8("tableWidget_documentazione"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_documentazione.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_documentazione.setHorizontalHeaderItem(1, item)
        self.tableWidget_documentazione.horizontalHeader().setCascadingSectionResizes(False)
        self.layoutWidget = QtGui.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 195, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_insert_row_documentazione = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_documentazione.setFont(font)
        self.pushButton_insert_row_documentazione.setObjectName(_fromUtf8("pushButton_insert_row_documentazione"))
        self.horizontalLayout_5.addWidget(self.pushButton_insert_row_documentazione)
        self.pushButton_remove_row_documentazione = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_documentazione.setFont(font)
        self.pushButton_remove_row_documentazione.setObjectName(_fromUtf8("pushButton_remove_row_documentazione"))
        self.horizontalLayout_5.addWidget(self.pushButton_remove_row_documentazione)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.dockWidget = QtGui.QDockWidget(self.tab_4)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_18 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 424, 235))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_20 = QtGui.QGridLayout(self.page)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_36 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_20.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_20.addWidget(self.label_9, 1, 0, 1, 2)
        self.comboBox_sito_rappcheck = QtGui.QComboBox(self.page)
        self.comboBox_sito_rappcheck.setEnabled(True)
        self.comboBox_sito_rappcheck.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_sito_rappcheck.setFont(font)
        self.comboBox_sito_rappcheck.setMouseTracking(True)
        self.comboBox_sito_rappcheck.setEditable(False)
        self.comboBox_sito_rappcheck.setMaxVisibleItems(99999)
        self.comboBox_sito_rappcheck.setMaxCount(2147483647)
        self.comboBox_sito_rappcheck.setObjectName(_fromUtf8("comboBox_sito_rappcheck"))
        self.comboBox_sito_rappcheck.addItem(_fromUtf8(""))
        self.gridLayout_20.addWidget(self.comboBox_sito_rappcheck, 2, 0, 1, 3)
        self.label_70 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_20.addWidget(self.label_70, 3, 0, 1, 2)
        self.label_48 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_20.addWidget(self.label_48, 6, 0, 1, 1)
        self.pushButton_crea_codice_periodo = QtGui.QPushButton(self.page)
        self.pushButton_crea_codice_periodo.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_crea_codice_periodo.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_crea_codice_periodo.setIcon(icon12)
        self.pushButton_crea_codice_periodo.setObjectName(_fromUtf8("pushButton_crea_codice_periodo"))
        self.gridLayout_20.addWidget(self.pushButton_crea_codice_periodo, 6, 1, 1, 2)
        self.lineEdit_codice_periodo = QtGui.QLineEdit(self.page)
        self.lineEdit_codice_periodo.setEnabled(False)
        self.lineEdit_codice_periodo.setObjectName(_fromUtf8("lineEdit_codice_periodo"))
        self.gridLayout_20.addWidget(self.lineEdit_codice_periodo, 6, 3, 1, 1)
        self.label_45 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_20.addWidget(self.label_45, 7, 0, 1, 1)
        self.pushButton_export_matrix = QtGui.QPushButton(self.page)
        self.pushButton_export_matrix.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_export_matrix.setFont(font)
        self.pushButton_export_matrix.setIcon(icon12)
        self.pushButton_export_matrix.setObjectName(_fromUtf8("pushButton_export_matrix"))
        self.gridLayout_20.addWidget(self.pushButton_export_matrix, 7, 1, 1, 2)
        self.pushButton_orderLayers = QtGui.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_orderLayers.setFont(font)
        self.pushButton_orderLayers.setObjectName(_fromUtf8("pushButton_orderLayers"))
        self.gridLayout_20.addWidget(self.pushButton_orderLayers, 8, 0, 1, 1)
        self.lineEditOrderLayer = QtGui.QLineEdit(self.page)
        self.lineEditOrderLayer.setEnabled(True)
        self.lineEditOrderLayer.setObjectName(_fromUtf8("lineEditOrderLayer"))
        self.gridLayout_20.addWidget(self.lineEditOrderLayer, 8, 1, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 209, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem4, 9, 2, 1, 1)
        self.comboBox_area_rappcheck = QtGui.QComboBox(self.page)
        self.comboBox_area_rappcheck.setObjectName(_fromUtf8("comboBox_area_rappcheck"))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.comboBox_area_rappcheck.addItem(_fromUtf8(""))
        self.gridLayout_20.addWidget(self.comboBox_area_rappcheck, 2, 3, 1, 1)
        self.pushButton_rapp_check = QtGui.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rapp_check.setFont(font)
        self.pushButton_rapp_check.setIcon(icon12)
        self.pushButton_rapp_check.setObjectName(_fromUtf8("pushButton_rapp_check"))
        self.gridLayout_20.addWidget(self.pushButton_rapp_check, 3, 2, 1, 1)
        self.line = QtGui.QFrame(self.page)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_20.addWidget(self.line, 4, 0, 1, 4)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 290, 222))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_21 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_38 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_21.addWidget(self.label_38, 0, 0, 1, 2)
        self.label_46 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_21.addWidget(self.label_46, 0, 2, 1, 2)
        self.toolButtonGis = QtGui.QToolButton(self.page_2)
        self.toolButtonGis.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonGis.setToolTip(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/GIS.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGis.setIcon(icon13)
        self.toolButtonGis.setCheckable(True)
        self.toolButtonGis.setChecked(False)
        self.toolButtonGis.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGis.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonGis.setObjectName(_fromUtf8("toolButtonGis"))
        self.gridLayout_21.addWidget(self.toolButtonGis, 1, 0, 1, 1)
        self.pushButton_showSelectedFeatures = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showSelectedFeatures.setFont(font)
        self.pushButton_showSelectedFeatures.setIcon(icon12)
        self.pushButton_showSelectedFeatures.setObjectName(_fromUtf8("pushButton_showSelectedFeatures"))
        self.gridLayout_21.addWidget(self.pushButton_showSelectedFeatures, 3, 0, 1, 2)
        self.label_39 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_21.addWidget(self.label_39, 4, 0, 1, 3)
        self.toolButtonPreview = QtGui.QToolButton(self.page_2)
        self.toolButtonPreview.setToolTip(_fromUtf8(""))
        self.toolButtonPreview.setIcon(icon13)
        self.toolButtonPreview.setCheckable(True)
        self.toolButtonPreview.setChecked(False)
        self.toolButtonPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreview.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreview.setObjectName(_fromUtf8("toolButtonPreview"))
        self.gridLayout_21.addWidget(self.toolButtonPreview, 5, 0, 1, 1)
        self.toolButtonPan = QtGui.QToolButton(self.page_2)
        self.toolButtonPan.setMinimumSize(QtCore.QSize(109, 0))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionPan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPan.setIcon(icon14)
        self.toolButtonPan.setCheckable(True)
        self.toolButtonPan.setChecked(False)
        self.toolButtonPan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPan.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPan.setObjectName(_fromUtf8("toolButtonPan"))
        self.gridLayout_21.addWidget(self.toolButtonPan, 5, 1, 1, 2)
        self.label_44 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_21.addWidget(self.label_44, 6, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem5, 8, 1, 1, 1)
        self.toolButtonPreviewMedia = QtGui.QToolButton(self.page_2)
        self.toolButtonPreviewMedia.setMinimumSize(QtCore.QSize(109, 0))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/photo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPreviewMedia.setIcon(icon15)
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setObjectName(_fromUtf8("toolButtonPreviewMedia"))
        self.gridLayout_21.addWidget(self.toolButtonPreviewMedia, 7, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 201, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem6, 8, 3, 1, 1)
        self.pushButton_showLayer = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showLayer.setFont(font)
        self.pushButton_showLayer.setIcon(icon12)
        self.pushButton_showLayer.setObjectName(_fromUtf8("pushButton_showLayer"))
        self.gridLayout_21.addWidget(self.pushButton_showLayer, 1, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_21.addWidget(self.label_40, 2, 0, 1, 2)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 614, 211))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.pushButton_exp_index_us = QtGui.QPushButton(self.page_3)
        self.pushButton_exp_index_us.setGeometry(QtCore.QRect(191, 30, 150, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exp_index_us.setFont(font)
        self.pushButton_exp_index_us.setIcon(icon12)
        self.pushButton_exp_index_us.setObjectName(_fromUtf8("pushButton_exp_index_us"))
        self.label_41 = QtGui.QLabel(self.page_3)
        self.label_41.setGeometry(QtCore.QRect(6, 0, 179, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.pushButton_pdf_exp = QtGui.QPushButton(self.page_3)
        self.pushButton_pdf_exp.setGeometry(QtCore.QRect(6, 30, 179, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pdf_exp.setFont(font)
        self.pushButton_pdf_exp.setIcon(icon12)
        self.pushButton_pdf_exp.setObjectName(_fromUtf8("pushButton_pdf_exp"))
        self.pushButton_exp_tavole = QtGui.QPushButton(self.page_3)
        self.pushButton_exp_tavole.setGeometry(QtCore.QRect(6, 70, 179, 24))
        self.pushButton_exp_tavole.setObjectName(_fromUtf8("pushButton_exp_tavole"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.gridLayout_18.addWidget(self.toolBox, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout_8.addWidget(self.dockWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_24.addWidget(self.tabWidget, 7, 0, 1, 17)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.comboBox_sito = QtGui.QComboBox(DialogGeo)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(306, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.comboBox_sito.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox_sito, 0, 0, 1, 1)
        self.label = QtGui.QLabel(DialogGeo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_10, 3, 0, 1, 8)

        self.retranslateUi(DialogGeo)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DialogGeo)
        DialogGeo.setTabOrder(self.comboBox_sito, self.lineEdit_progetto)
        DialogGeo.setTabOrder(self.lineEdit_progetto, self.comboBox_metodo)
        DialogGeo.setTabOrder(self.comboBox_metodo, self.lineEdit_anno)
        DialogGeo.setTabOrder(self.lineEdit_anno, self.lineEdit_settore)
        DialogGeo.setTabOrder(self.lineEdit_settore, self.comboBox_area)
        DialogGeo.setTabOrder(self.comboBox_area, self.lineEdit_griglia)
        DialogGeo.setTabOrder(self.lineEdit_griglia, self.tabWidget)
        DialogGeo.setTabOrder(self.tabWidget, self.textEdit_descrizione)
        DialogGeo.setTabOrder(self.textEdit_descrizione, self.textEdit_interpretazione)
        DialogGeo.setTabOrder(self.textEdit_interpretazione, self.pushButton_first_rec)
        DialogGeo.setTabOrder(self.pushButton_first_rec, self.pushButton_prev_rec)
        DialogGeo.setTabOrder(self.pushButton_prev_rec, self.pushButton_next_rec)
        DialogGeo.setTabOrder(self.pushButton_next_rec, self.pushButton_last_rec)
        DialogGeo.setTabOrder(self.pushButton_last_rec, self.pushButton_new_rec)
        DialogGeo.setTabOrder(self.pushButton_new_rec, self.pushButton_save)
        DialogGeo.setTabOrder(self.pushButton_save, self.pushButton_delete)
        DialogGeo.setTabOrder(self.pushButton_delete, self.pushButton_new_search)
        DialogGeo.setTabOrder(self.pushButton_new_search, self.pushButton_search_go)
        DialogGeo.setTabOrder(self.pushButton_search_go, self.pushButton_sort)
        DialogGeo.setTabOrder(self.pushButton_sort, self.pushButton_view_all)
        DialogGeo.setTabOrder(self.pushButton_view_all, self.pushButton_insert_row_documentazione)
        DialogGeo.setTabOrder(self.pushButton_insert_row_documentazione, self.pushButton_remove_row_documentazione)
        DialogGeo.setTabOrder(self.pushButton_remove_row_documentazione, self.pushButton_draw_doc)
        DialogGeo.setTabOrder(self.pushButton_draw_doc, self.pushButton)
        DialogGeo.setTabOrder(self.pushButton, self.tableWidget_documentazione)
        DialogGeo.setTabOrder(self.tableWidget_documentazione, self.comboBox_sito_rappcheck)
        DialogGeo.setTabOrder(self.comboBox_sito_rappcheck, self.pushButton_crea_codice_periodo)
        DialogGeo.setTabOrder(self.pushButton_crea_codice_periodo, self.lineEdit_codice_periodo)
        DialogGeo.setTabOrder(self.lineEdit_codice_periodo, self.pushButton_export_matrix)
        DialogGeo.setTabOrder(self.pushButton_export_matrix, self.pushButton_orderLayers)
        DialogGeo.setTabOrder(self.pushButton_orderLayers, self.lineEditOrderLayer)
        DialogGeo.setTabOrder(self.lineEditOrderLayer, self.comboBox_area_rappcheck)
        DialogGeo.setTabOrder(self.comboBox_area_rappcheck, self.pushButton_rapp_check)
        DialogGeo.setTabOrder(self.pushButton_rapp_check, self.toolButtonGis)
        DialogGeo.setTabOrder(self.toolButtonGis, self.pushButton_showSelectedFeatures)
        DialogGeo.setTabOrder(self.pushButton_showSelectedFeatures, self.toolButtonPreview)
        DialogGeo.setTabOrder(self.toolButtonPreview, self.toolButtonPan)
        DialogGeo.setTabOrder(self.toolButtonPan, self.toolButtonPreviewMedia)
        DialogGeo.setTabOrder(self.toolButtonPreviewMedia, self.pushButton_showLayer)
        DialogGeo.setTabOrder(self.pushButton_showLayer, self.pushButton_exp_index_us)
        DialogGeo.setTabOrder(self.pushButton_exp_index_us, self.pushButton_pdf_exp)
        DialogGeo.setTabOrder(self.pushButton_pdf_exp, self.pushButton_exp_tavole)

    def retranslateUi(self, DialogGeo):
        DialogGeo.setWindowTitle(_translate("DialogGeo", "pyArchInit Gestione Scavi - Scheda Geofisica", None))
        self.label_49.setText(_translate("DialogGeo", "Localizzazione Griglia", None))
        self.label_30.setText(_translate("DialogGeo", "Riferimenti", None))
        self.label_11.setText(_translate("DialogGeo", "Settore", None))
        self.label_rec_tot.setText(_translate("DialogGeo", "1", None))
        self.label_27.setText(_translate("DialogGeo", "record n.", None))
        self.label_rec_corrente.setText(_translate("DialogGeo", "1", None))
        self.label_28.setText(_translate("DialogGeo", "record tot.", None))
        self.label_34.setText(_translate("DialogGeo", "Status", None))
        self.label_43.setText(_translate("DialogGeo", "Ordinamento", None))
        self.label_42.setText(_translate("DialogGeo", "DB Info", None))
        self.pushButton_sort.setToolTip(_translate("DialogGeo", "Order by", None))
        self.pushButton_view_all.setToolTip(_translate("DialogGeo", "View alls records", None))
        self.pushButton_new_rec.setToolTip(_translate("DialogGeo", "New record", None))
        self.pushButton_save.setToolTip(_translate("DialogGeo", "Save", None))
        self.pushButton_search_go.setToolTip(_translate("DialogGeo", "search !!!", None))
        self.pushButton_last_rec.setToolTip(_translate("DialogGeo", "Last rec", None))
        self.pushButton_first_rec.setToolTip(_translate("DialogGeo", "First rec", None))
        self.pushButton_delete.setToolTip(_translate("DialogGeo", "Delete record", None))
        self.pushButton_next_rec.setToolTip(_translate("DialogGeo", "Next rec", None))
        self.pushButton_new_search.setToolTip(_translate("DialogGeo", "new search", None))
        self.pushButton_prev_rec.setToolTip(_translate("DialogGeo", "Prev rec", None))
        self.label_29.setText(_translate("DialogGeo", "DBMS Toolbar", None))
        self.label_5.setText(_translate("DialogGeo", "Metodo", None))
        self.comboBox_metodo.setItemText(0, _translate("DialogGeo", "Georadar", None))
        self.comboBox_metodo.setItemText(1, _translate("DialogGeo", "Elettromagnetismo", None))
        self.comboBox_metodo.setItemText(2, _translate("DialogGeo", "Magnetometria", None))
        self.comboBox_metodo.setItemText(3, _translate("DialogGeo", "Sismica", None))
        self.label_3.setText(_translate("DialogGeo", "<html><head/><body><p>Griglia</p></body></html>", None))
        self.label_61.setText(_translate("DialogGeo", "Anno", None))
        self.label_50.setText(_translate("DialogGeo", "Identificatori", None))
        self.label_47.setText(_translate("DialogGeo", "Topografici", None))
        self.label_4.setText(_translate("DialogGeo", "Progetto", None))
        self.label_15.setText(_translate("DialogGeo", "Quota assoluta", None))
        self.label_31.setText(_translate("DialogGeo", "Pdc", None))
        self.label_2.setText(_translate("DialogGeo", "Area", None))
        self.comboBox_area.setItemText(1, _translate("DialogGeo", "III", None))
        self.comboBox_area.setItemText(2, _translate("DialogGeo", "II", None))
        self.comboBox_area.setItemText(3, _translate("DialogGeo", "I", None))
        self.comboBox_area.setItemText(4, _translate("DialogGeo", "IV", None))
        self.comboBox_area.setItemText(5, _translate("DialogGeo", "V", None))
        self.comboBox_area.setItemText(6, _translate("DialogGeo", "1", None))
        self.comboBox_area.setItemText(7, _translate("DialogGeo", "2", None))
        self.comboBox_area.setItemText(8, _translate("DialogGeo", "3", None))
        self.comboBox_area.setItemText(9, _translate("DialogGeo", "4", None))
        self.comboBox_area.setItemText(10, _translate("DialogGeo", "5", None))
        self.comboBox_area.setItemText(11, _translate("DialogGeo", "6", None))
        self.comboBox_area.setItemText(12, _translate("DialogGeo", "7", None))
        self.comboBox_area.setItemText(13, _translate("DialogGeo", "8", None))
        self.comboBox_area.setItemText(14, _translate("DialogGeo", "9", None))
        self.comboBox_area.setItemText(15, _translate("DialogGeo", "10", None))
        self.comboBox_area.setItemText(16, _translate("DialogGeo", "11", None))
        self.comboBox_area.setItemText(17, _translate("DialogGeo", "12", None))
        self.comboBox_area.setItemText(18, _translate("DialogGeo", "13", None))
        self.comboBox_area.setItemText(19, _translate("DialogGeo", "14", None))
        self.comboBox_area.setItemText(20, _translate("DialogGeo", "15", None))
        self.comboBox_area.setItemText(21, _translate("DialogGeo", "16", None))
        self.comboBox_area.setItemText(22, _translate("DialogGeo", "17", None))
        self.comboBox_area.setItemText(23, _translate("DialogGeo", "18", None))
        self.comboBox_area.setItemText(24, _translate("DialogGeo", "19", None))
        self.comboBox_area.setItemText(25, _translate("DialogGeo", "20", None))
        self.label_13.setText(_translate("DialogGeo", "Dati descrittivi", None))
        self.textEdit_descrizione.setHtml(_translate("DialogGeo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:13pt;\"><br /></span></p></body></html>", None))
        self.label_6.setText(_translate("DialogGeo", "Descrizione ", None))
        self.label_7.setText(_translate("DialogGeo", "Interpretazione ", None))
        self.label_25.setText(_translate("DialogGeo", "Data schedatura", None))
        self.label_35.setText(_translate("DialogGeo", "Schedatore", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogGeo", "Dati descrittivi", None))
        self.label_59.setText(_translate("DialogGeo", "Asse z", None))
        self.label_60.setText(_translate("DialogGeo", "Asse y", None))
        self.label_58.setText(_translate("DialogGeo", "Asse x", None))
        self.label_65.setText(_translate("DialogGeo", "m", None))
        self.label_66.setText(_translate("DialogGeo", "m", None))
        self.label_67.setText(_translate("DialogGeo", "m", None))
        self.label_57.setText(_translate("DialogGeo", "Dati Georadar", None))
        self.label_51.setText(_translate("DialogGeo", "Risoluzione", None))
        self.label_54.setText(_translate("DialogGeo", "Massima profondità stimata", None))
        self.label_53.setText(_translate("DialogGeo", "Range(ns)", None))
        self.label_52.setText(_translate("DialogGeo", "Frequenza antenna", None))
        self.label_55.setText(_translate("DialogGeo", "TextLabel", None))
        self.label_56.setText(_translate("DialogGeo", "TextLabel", None))
        self.comboBox_frequenza.setItemText(1, _translate("DialogGeo", "100", None))
        self.comboBox_frequenza.setItemText(2, _translate("DialogGeo", "200", None))
        self.comboBox_frequenza.setItemText(3, _translate("DialogGeo", "300", None))
        self.comboBox_frequenza.setItemText(4, _translate("DialogGeo", "400", None))
        self.comboBox_frequenza.setItemText(5, _translate("DialogGeo", "500", None))
        self.comboBox_frequenza.setItemText(6, _translate("DialogGeo", "200-600", None))
        self.comboBox_frequenza.setItemText(7, _translate("DialogGeo", "400-600", None))
        self.label_62.setText(_translate("DialogGeo", "Riferimenti Griglia", None))
        self.label_63.setText(_translate("DialogGeo", "Modello Georadar", None))
        self.comboBox.setItemText(0, _translate("DialogGeo", "IDS", None))
        self.label_64.setText(_translate("DialogGeo", "Calcolo velocità", None))
        self.comboBox_2.setItemText(0, _translate("DialogGeo", "Metodo dell\'asta metallica", None))
        self.label_68.setText(_translate("DialogGeo", "Data Survey", None))
        self.label_69.setText(_translate("DialogGeo", "Slice", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("DialogGeo", "GPR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogGeo", "Magnetometria", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogGeo", "Elettromagnetismo", None))
        self.pushButton_draw_doc.setText(_translate("DialogGeo", "Visualizza documentazione", None))
        self.pushButton.setText(_translate("DialogGeo", "Aggiorna doc", None))
        item = self.tableWidget_documentazione.horizontalHeaderItem(0)
        item.setText(_translate("DialogGeo", "Tipo documentazione", None))
        item = self.tableWidget_documentazione.horizontalHeaderItem(1)
        item.setText(_translate("DialogGeo", "Riferimenti", None))
        self.pushButton_insert_row_documentazione.setText(_translate("DialogGeo", "inserisci riga", None))
        self.pushButton_remove_row_documentazione.setText(_translate("DialogGeo", "rimuovi riga", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("DialogGeo", "Documentazione", None))
        self.label_36.setText(_translate("DialogGeo", "TOOLS", None))
        self.label_9.setText(_translate("DialogGeo", "Selezione del sito per i controlli", None))
        self.comboBox_sito_rappcheck.setItemText(0, _translate("DialogGeo", "Inserisci un valore", None))
        self.label_70.setText(_translate("DialogGeo", "Check rapporti stratigrafici", None))
        self.label_48.setText(_translate("DialogGeo", "Crea Codice Periodo", None))
        self.pushButton_crea_codice_periodo.setToolTip(_translate("DialogGeo", "Show Selcted Features", None))
        self.pushButton_crea_codice_periodo.setText(_translate("DialogGeo", "Crea codice periodo", None))
        self.label_45.setText(_translate("DialogGeo", "Esporta Matrix", None))
        self.pushButton_export_matrix.setToolTip(_translate("DialogGeo", "Export PDF", None))
        self.pushButton_export_matrix.setText(_translate("DialogGeo", "export Matrix", None))
        self.pushButton_orderLayers.setText(_translate("DialogGeo", "Ordine Stratigrafico", None))
        self.comboBox_area_rappcheck.setItemText(0, _translate("DialogGeo", "1", None))
        self.comboBox_area_rappcheck.setItemText(1, _translate("DialogGeo", "2", None))
        self.comboBox_area_rappcheck.setItemText(2, _translate("DialogGeo", "3", None))
        self.comboBox_area_rappcheck.setItemText(3, _translate("DialogGeo", "4", None))
        self.comboBox_area_rappcheck.setItemText(4, _translate("DialogGeo", "5", None))
        self.comboBox_area_rappcheck.setItemText(5, _translate("DialogGeo", "6", None))
        self.comboBox_area_rappcheck.setItemText(6, _translate("DialogGeo", "7", None))
        self.comboBox_area_rappcheck.setItemText(7, _translate("DialogGeo", "8", None))
        self.comboBox_area_rappcheck.setItemText(8, _translate("DialogGeo", "9", None))
        self.comboBox_area_rappcheck.setItemText(9, _translate("DialogGeo", "10", None))
        self.pushButton_rapp_check.setToolTip(_translate("DialogGeo", "Export PDF", None))
        self.pushButton_rapp_check.setText(_translate("DialogGeo", "Check, go!!!!", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("DialogGeo", "Sistemi di controllo", None))
        self.label_38.setText(_translate("DialogGeo", "Visualizzazione GIS", None))
        self.label_46.setText(_translate("DialogGeo", "Disegna Griglia", None))
        self.toolButtonGis.setText(_translate("DialogGeo", "GIS Data Visualizer", None))
        self.toolButtonGis.setShortcut(_translate("DialogGeo", "Ctrl+G", None))
        self.pushButton_showSelectedFeatures.setToolTip(_translate("DialogGeo", "Show Selcted Features", None))
        self.pushButton_showSelectedFeatures.setText(_translate("DialogGeo", "Apri schede Griglia", None))
        self.label_39.setText(_translate("DialogGeo", "Attivazione Preview Griglia", None))
        self.toolButtonPreview.setText(_translate("DialogGeo", "Preview Griglia", None))
        self.toolButtonPreview.setShortcut(_translate("DialogGeo", "Ctrl+G", None))
        self.toolButtonPan.setToolTip(_translate("DialogGeo", "Pan tool", None))
        self.toolButtonPan.setText(_translate("DialogGeo", "Pan", None))
        self.toolButtonPan.setShortcut(_translate("DialogGeo", "Ctrl+G", None))
        self.label_44.setText(_translate("DialogGeo", "Mostra immagini", None))
        self.toolButtonPreviewMedia.setText(_translate("DialogGeo", "Mostra immagini", None))
        self.pushButton_showLayer.setToolTip(_translate("DialogGeo", "Show Selcted Features", None))
        self.pushButton_showLayer.setText(_translate("DialogGeo", "Disegna Griglia", None))
        self.label_40.setText(_translate("DialogGeo", "Apri schede Griglia", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("DialogGeo", "Funzioni di controllo", None))
        self.pushButton_exp_index_us.setText(_translate("DialogGeo", "Elenco Griglie", None))
        self.label_41.setText(_translate("DialogGeo", "Esportazioni PDF/PNG", None))
        self.pushButton_pdf_exp.setToolTip(_translate("DialogGeo", "Export PDF", None))
        self.pushButton_pdf_exp.setText(_translate("DialogGeo", "Singole schede", None))
        self.pushButton_exp_tavole.setText(_translate("DialogGeo", "Espotazione Tavole", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("DialogGeo", "Esportazioni", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("DialogGeo", "Tools", None))
        self.comboBox_sito.setItemText(0, _translate("DialogGeo", "Inserisci un valore", None))
        self.label.setText(_translate("DialogGeo", "Sito ", None))

import resources_rc
